### POST route for login
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "Tim",
  "password": "Timmothy1!"
}

### POST route for signup
###
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

### GET route for github access token
###
GET http://localhost:3000/api/auth/login
accept: application/json


### Testing github request
POST https://github.com/login/oauth/access_token?
    client_id = Ov23liYM1ozG09dkyK5s &
    client_secret = d687f482fe2ac3379e640ef98022ad91194806e3 &
    code = 5d95e3381adfc432eeec

    Content-Type: application/json

### Testing GitHub user data
GET https://api.github.com/user
Content-Type: application/json